version: "3.8"
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
  demo:
    build: .
    restart: always
    ports:
      - "8080:8080"
    links:
      - mongo-express
